kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-full-access-clusterrole
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-full-access-clusterrolebinding
subjects:
- kind: User
  name: eksworkspace-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: eks-full-access-clusterrole
  apiGroup: rbac.authorization.k8s.io
